<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Login successfully executed]]>
    </line>
  </reporter-output>
  <suite started-at="2020-10-24T14:04:26Z" name="Data Driven Basics" finished-at="2020-10-24T14:04:27Z" duration-ms="1129">
    <groups>
    </groups>
    <test started-at="2020-10-24T14:04:26Z" name="BankManagerLoginTest" finished-at="2020-10-24T14:04:26Z" duration-ms="179">
      <class name="com.way2a.testcases.BankManagerLoginTest">
        <test-method signature="loginAsBankManager()[pri:0, instance:com.way2a.testcases.BankManagerLoginTest@7e7b159b]" started-at="2020-10-24T19:34:26Z" name="loginAsBankManager" finished-at="2020-10-24T19:34:26Z" duration-ms="163" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Login successfully executed]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- com.way2a.testcases.BankManagerLoginTest -->
    </test> <!-- BankManagerLoginTest -->
    <test started-at="2020-10-24T14:04:26Z" name="Add Customer Test" finished-at="2020-10-24T14:04:27Z" duration-ms="889">
      <class name="com.way2a.testcases.AddCustomerTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.way2a.testcases.AddCustomerTest@333dd51e]" started-at="2020-10-24T19:34:17Z" name="setUp" finished-at="2020-10-24T19:34:26Z" duration-ms="9121" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addCustomer(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.way2a.testcases.AddCustomerTest@333dd51e]" started-at="2020-10-24T19:34:26Z" name="addCustomer" data-provider="getData" finished-at="2020-10-24T19:34:27Z" duration-ms="850" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[nishanth]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[sm]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[560072.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Customer not added]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Customer not added
	at org.testng.Assert.fail(Assert.java:93)
	at com.way2a.testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:22)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.way2a.testcases.AddCustomerTest@333dd51e]" started-at="2020-10-24T19:34:27Z" name="tearDown" finished-at="2020-10-24T19:34:28Z" duration-ms="770" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.way2a.testcases.AddCustomerTest -->
    </test> <!-- Add Customer Test -->
  </suite> <!-- Data Driven Basics -->
</testng-results>
